### ISSUE TITLE
本项目API文档

### ISSUE THREAD

**Issue by Aliorpse** [Ohdmire/ATRIbot#7]
部署了项目，在localhost:8008启动了一个接口服务器
请问能给出这个API的详细文档吗，不太会python，看的有点吃力

**Comment by Ohdmire** [comment]
现在项目部署还不够完善 等我之后弄个docker出来再说吧 现在是nonebot的那部分我还没传GitHub api在main.py里面 url地址按照post请求传

**Comment by Aliorpse** [comment]
好的，等你前端
_（小声:我用的不是nonebot）_
